
services:
  postgres:
    image: postgres:17-alpine
    container_name: monitoringDB
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - monitor-network
networks:
  monitor-network:
    driver: bridge