events {
    worker_connections 1024;
}

# Cấu hình TCP (Layer 4) để Load Balancing luồng log gửi từ Agent lên các Worker Node trên cổng 8080
stream {
    upstream worker_tcp_pool {
        server localhost:3001;
        server localhost:3002;
        server localhost:3003;
    }

    server {
        listen 8080; # Cổng nhận kết nối TCP của Agent (trước đây là HTTP)
        proxy_pass worker_tcp_pool;
        proxy_timeout 10m;
        proxy_connect_timeout 5s;
    }
}