upstream worker_pool {
    server localhost:3001;
    server localhost:3002;
    server localhost:3003;
}

# --- MASTER NODE (Lắng nghe HTTPS ở Port 3000) ---
server {
    listen 3000 ssl;
    server_name localhost;

    ssl_certificate /media/ubuntu/DISK_D5/LEARN/Lap_Trinh_Mang_Can_Ban/project/NT106.Q23.ANTT-PRJ/src/nginx/ssl/nginx.crt;
    ssl_certificate_key /media/ubuntu/DISK_D5/LEARN/Lap_Trinh_Mang_Can_Ban/project/NT106.Q23.ANTT-PRJ/src/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Chuyển tất cả request (bao gồm /api/agent/handshake, /api/auth...) xuống Node.js chạy ở port 3005
    location / {
        proxy_pass http://localhost:3005;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# --- LOAD BALANCER / WORKER POOL (Lắng nghe HTTPS ở Port 8080) ---
server {
    listen 8080 ssl;
    server_name localhost;

    ssl_certificate /media/ubuntu/DISK_D5/LEARN/Lap_Trinh_Mang_Can_Ban/project/NT106.Q23.ANTT-PRJ/src/nginx/ssl/nginx.crt;
    ssl_certificate_key /media/ubuntu/DISK_D5/LEARN/Lap_Trinh_Mang_Can_Ban/project/NT106.Q23.ANTT-PRJ/src/nginx/ssl/nginx.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Chuyển request xuống các Worker
    location / {
        proxy_pass http://worker_pool;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
