# Cấu hình TCP (Layer 4) để Load Balancing luồng log gửi từ Agent lên các Worker Node trên cổng 8080
stream {
    upstream worker_tcp_pool {
        server 100.98.64.127:3001;
        server 100.98.64.127:3002;
        server 100.98.64.127:3003;
    }

    server {
        listen 8080; # Cổng nhận kết nối TCP của Agent 
        proxy_pass worker_tcp_pool;
        proxy_timeout 10m;
        proxy_connect_timeout 5s;
    }
}