version: '3.8'
services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: k13t_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=monitor_db
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # Store data (not lost if turn off / delete postgresql container Docker)
      # ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
